### ISSUE TITLE
Error Loading Default Project

### ISSUE THREAD

**Issue by darylounet** [whitefire/eZ-completion#4]
I can't open any kind of project when the plugin is enabled : 
```
com.intellij.diagnostic.PluginException:Framework/CompletionPreloader : Unsupported major.minor version 51.0 [Plugin: com.flageolett.eZ.completion] [Plugin: com.flageolett.eZ.completion]
```
![capture d ecran 2015-01-12 a 09 22 02](https://cloud.githubusercontent.com/assets/203083/5700353/20ab41e4-9a3d-11e4-9c61-996085f0f317.png)
I'm running PhpStorm 8.0.2 on MacOS X 10.10 (Yosemite) with Apple's JRE (1.6.0_65).

**Comment by whitefire** [comment]
I'm sorry to hear that.

I had some serious performance issues with PhpStorm 8 on Yosemite, so I went back and forth between the regular 8.02 and the custom-build with Java 1.7. I must have ended up with the latter.

I hope you were able to easily disable the plugin and go on with your day.
I will recompile and resubmit shortly.

**Comment by darylounet** [comment]
No problem, the settings menu is still accessible and the plugin can easily be disabled.

I had the same performance issues with PhpStorm custom build with Java 1.7 on a MacBookAir6,2. That's why I also rolled back to the regular one with Apple's official Java 1.6.

**Comment by whitefire** [comment]
A new version compiled for java 1.6  is available here: https://github.com/whitefire/eZ-completion/raw/dev/eZ.jar.
Will you please give it a try? :)

**Comment by darylounet** [comment]
It works, I can open my projects but I have this error in Event Log : 
```
11:38:03 Failed: ezcode:completion
         [InvalidArgumentException]                                
         There are no commands defined in the "ezcode" namespace.  
```

**Comment by whitefire** [comment]
Have you installed and activated this bundle: https://github.com/whitefire/ez-completion-bundle?

**Comment by darylounet** [comment]
Not on the project I was actually working on :( Thank you for the Java 1.6 build !

**Comment by whitefire** [comment]
I will try to embed the bundle somwhow in a future verison! Thanks for testing! :)
