### ISSUE TITLE
Failed: ezcode:completion

### ISSUE THREAD

**Issue by kemoc** [whitefire/eZ-completion#8]
Hi, if you have time please take care this. I have exception in PHPStorm 2016.2
Java Oracle 8 x64:

> Failed: ezcode:completion
    java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 1 path $

If you need i can send you this string generated by
`php app/console ezcode:completition`

**Comment by whitefire** [comment]
Hi! 

So glad to hear that someone is actually using the plugin! :-)

If you could post the output as a gist, it would be much appreciated. 

On a side note: I would love some user feedback if you have any! :-)

**Comment by Haehnchen** [comment]
> So glad to hear that someone is actually using the plugin! :-)

This made my day. had the same experiences 4 years ago :)

**Comment by whitefire** [comment]
Hehe! That's cool to hear! :-) The lack of issues has made me think that either the code works unusually well, or no one is using the plugin! :-)

There's always the plugin download statistics, but they seem somewhat high.

**Comment by kemoc** [comment]
@whitefire :) you're welcome:
https://gist.github.com/kemoc/e3706c2b659c533598123a2c75189ec4

**Comment by kemoc** [comment]
I think the problem are '"' not escaped but I'm not sure. JSON seems to look correctly.
or something other, i'm not good in Java, i know only basics but in PHPStorm your dump has not any error (i have opened it as JSON file)
i have found, maybe our problem is similar:
http://stackoverflow.com/questions/34917713/retrofit-java-lang-illegalstateexception-expected-begin-array-but-was-begin-o

**Comment by whitefire** [comment]
Some node in the JSON has a different value than the serialization-target is expecting. I've seen the message before while writing the code.
I'm travelling today, but will take a look at it either tonight or tomorrow.

**Comment by kemoc** [comment]
These are special chars from Polish lang (It's my native language and person for who i make the project) like: 'ąćęłóśźż' but these are in UTF-8. If you need export classes always in eng-GB.

**Comment by whitefire** [comment]
@kemoc: Unable to reproduce the issue in 2017.1.1, have you tried/considered upgrading?

You could also try to delete the files stored here: ~/Library/Application Support/PhpStorm2016-something-something-darkside/EzPlugin. 
Pretty sure I don't cache invalid responses, but you never know! :)

**Comment by kemoc** [comment]
Hi @whitefire 
You're right, this cache was a problem. Before remove it i open file and there has been at the begin:

> Warning:

 chmod(): Operation not permitted in /project-path/ezpublish_legacy/lib/ezutils/classes/ezphpcreator.php on line 955
...

i have removed this directory and now file there is correct but plugin is still Disabled, i have resterted PHPStorm, invalidate cache and restart again and nothing happen.

**Comment by kemoc** [comment]
@whitefire please, could you add link to this repo and requirements to plugin information to read it in PHPStorm plugin repository?

**Comment by whitefire** [comment]
Seems like I cache invalid responses after all, not good.

The failing code seems to be part of eZ and not the plugin itself. I should however add a note regarding caching of invalid responses until the issue is resolved. Agreed?

**Comment by kemoc** [comment]
Ok, and as fast as is possible add link to readme on plugin in phpstorm plugin repo, thanks.

**Comment by whitefire** [comment]
I've uploaded a new version with better handling of invalid responses.
JetBrains says it will be available within 2 business days.

If impatience strikes, you can fetch the latest version [here](https://github.com/whitefire/eZ-completion/blob/v1.0.4.1/eZ-completion.jar)

**Comment by kemoc** [comment]
Thanks, i'm be able to wait

**Comment by annitya** [comment]
Readme was also updated btw.
