### ISSUE TITLE
Field completition seems does not work

### ISSUE THREAD

**Issue by kemoc** [whitefire/eZ-completion#9]
Twig:
`{% set myLocation = content.getFieldValue('location') %}
 {% set myLocation = content.getField('location') %}
 {{ ez_render_field(content, 'loca') }}`
does not work.
and when next versions;) 1.0.5, 1.0.6?
Maybe next version (i mean 1.0.7) should complete view params in TWIG dynamically, detect controller - service for template and complete variables names :))

**Comment by whitefire** [comment]
What contentType does the content-variable contain?

I know @Haehnchen has made some efforts regarding automatic variable-completion in Twig templates, but I never could get it to work.

It's a difficult challenge, because there are so many code-paths that needs to be resolved to properly ascertain the type of said variables.

@Haehnchen: What's the current status on this?

**Comment by kemoc** [comment]
@whitefire I see that for elwira_z_photographic_company_homepage, elwira_z_contact but i think is that for any contentType,
when match is that:
`
match:
       Identifier\ContentType: "elwira_z_photographic_company_homepage"
`
below completition works
{% if not ez_is_field_empty( content, "description_simple" ) %}
occure works:
{{ ez_render_field(content, 'location') }}
but not:
{{ content.getFieldValue('description_simple').text|nl2br }}
{{ content.getField('description_simple') }}

when match is that:
`
match:
       Identifier\ContentType: ["elwira_z_photographic_company_homepage"]
`doesn't work:
{% if not ez_is_field_empty( content, "description_simple" ) %}
{{ ez_render_field(content, 'location') }}

and i do not know when:
`
match:
      Identifier\Section: "elwira_z_media"
      Identifier\ContentType: "elwira_z_images_folder"
`

**Comment by kemoc** [comment]
https://plugins.jetbrains.com/plugin/7219-symfony-plugin
it seems i need the PHPStorm update.

**Comment by kemoc** [comment]
@whitefire after upgrade PHPStorm to 2017.1 and Symfony plugin i still have these problems, nothing is better:/

**Comment by whitefire** [comment]
Thanks for letting me now. I'll start work on it later today! :)

**Comment by whitefire** [comment]
For:
```
match:
       Identifier\ContentType: ["elwira_z_photographic_company_homepage"]
```
I suggest you remove the brackets. Brackets are used to specify more than one contentType that matches and you have only one. If there are more then one contentType, then completions can't be automatically inferred.

**Comment by whitefire** [comment]
```
match:
      Identifier\Section: "elwira_z_media"
      Identifier\ContentType: "elwira_z_images_folder"
```
This one works as expected for both section and contentType.

**Comment by kemoc** [comment]
> I suggest you remove the brackets.

Ok, i will. What with completition:
```
{{ content.getFieldValue('description_simple').text|nl2br }}
{{ content.getField('description_simple').value.text|nl2br }}
{% set fieldItem = content.getField('description_simple') %}
```
can you do something with it?

**Comment by kemoc** [comment]
@whitefire comment above, please answer

**Comment by annitya** [comment]
Done! :)

Version 1.04.1 was already published by JetBrains, so latest version is now 1.0.4.2.
I suspect 1.0.4.2 will be made quickly available as well, if not; you can find it [here](https://github.com/whitefire/eZ-completion/blob/v1.0.4.2/eZ-completion.jar)

**Comment by kemoc** [comment]
Nice job, vodka for you:)

**Comment by annitya** [comment]
Tomorrow! :-D

**Comment by kemoc** [comment]
I have bad news, i have not any completition now:(

**Comment by annitya** [comment]
Crap! And I already left the office. Not anywhere? What about within php-code?

**Comment by kemoc** [comment]
No problem, it was [], but before plugin updates it not damaged whole completition but only for specific content

**Comment by annitya** [comment]
Hmm! I'll have to test tomorrow!

**Comment by annitya** [comment]
Could you explain in greater detail what happened? Did using brackets in the view-configuration break all completions everywhere, or only in twig?

**Comment by kemoc** [comment]
@whitefire I was using '[class_identifier]' as you remember for homepage and in 1.0.4.2 plugin version it damaged completition in all TWIG files, everywhere, about PHP i do not know because even i removed '[]' from YML file in PHP completition doesn't work.

**Comment by kemoc** [comment]
PS: I do not know where (which files) this plugin help too? I do not understand well your plugin description.

**Comment by annitya** [comment]
Every possible completion can be seen [here](https://github.com/whitefire/ez-completion-bundle/tree/master/Examples). It is mentioned in the readme, but some documentation would probably be much better. I will do some testing during the weekend and try to locate what breaks completion.

**Comment by kemoc** [comment]
Thanks, so i tested:
`$content->getFieldValue('title');`
and didn't work but i need to try again, maybe i made some mistake. Tomorrow i will have time.

**Comment by kemoc** [comment]
@whitefire Hi, i have checked controller and there completition doesn't work:
```
        $content = $view->getContent();
        $zz = $content->getFieldValue("");
        $zz = $content->getField("");
```
my controller:
```
    public function viewAction(ContentView $view)
    {
    	$view = parent::viewAction($view);

        $viewParams = [];
        $request = $this->getRequest();

        $entity = new ContactMessage();
        $form = $this->getForm($entity);
        $form->handleRequest($request);
        $content = $view->getContent();
        $zz = $content->getFieldValue("");
        $zz = $content->getField("");
```
my controller class extends \eZ\Publish\Core\MVC\Symfony\Controller\Content\ViewController
it's recomended for eZ Platform custom controllers (see ViewController)
and that new controller must be a service. Also i see in view YML configuration the parameter 
`controller: "..."` is not clickable, no suggestion,
`template: "..."` sugestion, click works but popup should be always under mouse pointer, it is not when popup is widther than screen

**Comment by annitya** [comment]
Available completions are not auto-detected in controllers yet. Try adding a comment on the following format (think PHPDoc): 
```
/** @ContentType some_content_type $someVariable */
```
Clickable controllers in twig-files hasn't been implemented yet, so I would be very surprised if that worked! :)

**Comment by annitya** [comment]
I'm not able to reproduce the issue with [] breaking completion in all twig-files. Could you perhaps provide me with a minimal code-example for this?

**Comment by kemoc** [comment]
@whitefire now i can't reproduce it too, ok i think is good

**Comment by annitya** [comment]
I have created a blog-post documenting how to use the plugin [here](http://waitofaiorur.blogspot.no/2017/04/development-with-ez-publish-and-phpstorm.html).
